const screenOperation=document.getElementById('screen-operation');const screenResult=document.getElementById('screen-result');const buttons=document.getElementById('buttons');let stateDelete=!0;let stateEqual=!1;const lastValue=()=>{return screenOperation.textContent.charAt(screenOperation.textContent.length-1)}
const deleteSimbol=()=>{if(stateDelete){if(screenOperation.textContent.length>1){screenOperation.textContent=screenOperation.textContent.slice(0,-1)}else{screenOperation.textContent='0'}}}
const writeOperation=(text)=>{if(screenOperation.textContent==='0'){if(text==='.'){screenOperation.textContent='0'}else{screenOperation.textContent=''}}
if(isNaN(lastValue())&&isNaN(text)){screenOperation.textContent=screenOperation.textContent.slice(0,-1)}
if(!isNaN(lastValue())&&stateEqual){if(isNaN(text)){screenOperation.textContent=screenResult.textContent+text;text='';stateEqual=!1}else{screenOperation.textContent=text;stateEqual=!1;text=''}}
screenOperation.textContent+=text}
const writeResult=()=>{stateDelete=!1;stateEqual=!0;screenResult.textContent=stringToValue(screenOperation.textContent)}
const changeSign=()=>{let lastNumber='';let sign='';let parentesis=!1;if(lastValue()===')'){for(let i=1;i<screenOperation.textContent.length;i ++){if(!isNaN(screenOperation.textContent[screenOperation.textContent.length-1-i])){lastNumber+=screenOperation.textContent[screenOperation.textContent.length-1-i]}else{sign='(-)';break}}}else if(isNaN(lastValue)&&lastValue()!=='0'){for(let i=0;i<screenOperation.textContent.length;i ++){if(!isNaN(screenOperation.textContent[screenOperation.textContent.length-1-i])){lastNumber+=screenOperation.textContent[screenOperation.textContent.length-1-i]}else{sign=screenOperation.textContent[screenOperation.textContent.length-1-i];break}}}
lastNumber=lastNumber.split('').reverse().join('');console.log(lastNumber,sign);switch(sign){case '':screenOperation.textContent=screenOperation.textContent.replace(lastNumber,`-${lastNumber}`);break;case '*':case '/':screenOperation.textContent=screenOperation.textContent.replace(lastNumber,`(-${lastNumber})`);break;case '-':screenOperation.textContent=screenOperation.textContent.replace(`-${lastNumber}`,`+${lastNumber}`);break;case '(-)':screenOperation.textContent=screenOperation.textContent.replace(`(-${lastNumber})`,`${lastNumber}`);break;case '+':screenOperation.textContent=screenOperation.textContent.replace(`+${lastNumber}`,`-${lastNumber}`);break}}
const stringToValue=(str)=>{return new Function(`'use strict'; return ${str}`)()}
const resetScreen=()=>{stateDelete=!0;stateEqual=!1;screenOperation.textContent='0';screenResult.textContent='0'}
buttons.addEventListener('click',(e)=>{if(e.target.id.includes("button")){switch(e.target.id){case "button-clear":resetScreen();break;case "button-sign":changeSign();break;case "button-equal":writeResult();break;case "button-dot":writeOperation('.');break;case "button-delete":case "button-delete-span":deleteSimbol();break;default:writeOperation(e.target.textContent);break}}})